"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Lang = "en" | "bn";

const translations = {
  en: {
    navHome: "Home",
    navServices: "Services",
    navPricing: "Pricing",
    navPortfolio: "Our Demo",
    navTeam: "Team",
    navWhyUs: "Why Us",
    navContact: "Contact",
    navAbout: "About",
    navFaq: "FAQ",
    navPrivacy: "Privacy Policy",
    navTerms: "Terms & Conditions",
    navCta: "Get Started",
    navMore: "More",
    navSectionMain: "Main",
    navSectionInfo: "Info",
    navSectionAccount: "Account",
    navProfile: "Profile",
    navAdminPanel: "Admin Panel",
    navSignOut: "Sign Out",
    navSignIn: "Sign In",
    navCreateAccount: "Create Account",
    cart: "Cart",

    heroBadge: "Rasel Cloud Team — Full-Service Digital Agency",
    heroHeading1: "We Build, Grow &",
    heroHeading2: "Transform",
    heroHeading3: "Your Digital Presence.",
    heroSub1: "Welcome to",
    heroName: "rasel.cloud",
    heroSub2: " — a multi-service digital agency delivering custom web solutions, AI automation, SEO growth, and creative media for businesses of every scale.",
    heroCtaPrimary: "Get a Free Consultation",
    heroCtaSecondary: "Our Demo",
    heroProjects: "Projects",
    heroClients: "Clients",
    heroYears: "Years",
    typewriterWords: ["Web Development", "AI Automation", "SEO & Growth", "Video Editing", "Brand Design", "Admin Panels"],

    statsProjects: "Projects Completed",
    statsClients: "Happy Clients",
    statsSatisfaction: "Client Satisfaction",
    statsSupport: "Support Available",

    servicesTag: "What We Offer",
    servicesHeading: "Our Core",
    servicesHeadingHighlight: "Services",
    svcWebTitle: "Custom Web & Admin Panels",
    svcWebDesc: "Enterprise-grade websites, admin dashboards, e-commerce platforms, and management systems. Scalable, secure, and pixel-perfect.",
    svcAiTitle: "AI Agent Automation",
    svcAiDesc: "Deploy intelligent AI agents for social media, website chatbots, and business workflows. Automate tasks on autopilot.",
    svcSeoTitle: "SEO & Digital Growth",
    svcSeoDesc: "Dominate search rankings with technical SEO, content strategy, and performance optimization.",
    svcCreativeTitle: "Creative Media & Design",
    svcCreativeDesc: "Professional video editing, motion graphics, biography design, brand identity, and social media content creation.",
    svcLearnMore: "Learn More",
    svcAddToCart: "Add to Cart",
    svcBuyNow: "Buy Now",

    processTag: "How We Work",
    processHeading: "Our",
    processHeadingHighlight: "Process",
    proc1Title: "Discovery & Strategy",
    proc1Desc: "We analyze your business, audience, and competition to build a custom strategy.",
    proc2Title: "Design & Prototype",
    proc2Desc: "Pixel-perfect designs and interactive prototypes that bring your vision to life.",
    proc3Title: "Development & Integration",
    proc3Desc: "Clean, performant code with AI integrations, SEO optimization, and third-party APIs.",
    proc4Title: "Launch & Scale",
    proc4Desc: "Rigorous testing, deployment, ongoing support, and growth strategy.",

    portfolioTag: "Live Demos",
    portfolioHeading: "Our",
    portfolioHeadingHighlight: "Demo",
    port1Title: "BD Order Solution",
    port1Cat: "E-commerce Platform",
    port1Desc: "All-in-one WooCommerce checkout manager with bKash/Nagad payment integration.",
    port1Metric: "Increased sales by 40%",
    port2Title: "Kariana Quran Web App",
    port2Cat: "Full-Stack Web App",
    port2Desc: "Comprehensive Islamic tools suite with Quran reading and prayer times.",
    port2Metric: "10K+ active users",
    port3Title: "Herbo Cure Management",
    port3Cat: "Enterprise Dashboard",
    port3Desc: "Healthcare practitioner dashboard for patient management and analytics.",
    port3Metric: "Efficiency up 60%",
    port4Title: "AI Agents & DevOps",
    port4Cat: "AI Automation",
    port4Desc: "Autonomous AI agents for social media management and content generation.",
    port4Metric: "5x faster operations",

    testTag: "Client Stories",
    testHeading: "What Clients",
    testHeadingHighlight: "Say",

    techTag: "Our Tech Arsenal",
    techHeading: "Tech",
    techHeadingHighlight: "Stack",

    roiTag: "See the Impact",
    roiHeading: "AI ROI",
    roiHeadingHighlight: "Calculator",
    roiHoursLabel: "Hours spent on manual tasks / week",
    roiRateLabel: "Your hourly rate ($)",
    roiResult: "With our AI automation, you could save",
    roiHours: "hours/week",
    roiMoney: "/year",
    roiCta: "Let's Automate Your Business",

    faqTag: "Common Questions",
    faqHeading: "Frequently",
    faqHeadingHighlight: "Asked",
    faq1Q: "What services does rasel.cloud offer?",
    faq1A: "We offer custom web development, admin panels, AI automation, SEO, video editing, biography design, and full brand identity packages.",
    faq2Q: "How long does a typical project take?",
    faq2A: "Landing pages: 1-2 weeks, admin panels: 3-6 weeks, enterprise AI: 4-8 weeks.",
    faq3Q: "Do you work with large companies?",
    faq3A: "Absolutely. We specialize in enterprise-grade solutions.",
    faq4Q: "What's your pricing model?",
    faq4A: "We offer fixed-price, milestone-based, and retainer models.",
    faq5Q: "Can you handle SEO alongside development?",
    faq5A: "Yes! We handle everything from building your website to ranking it on Google.",

    ctaHeading1: "Ready to",
    ctaHeadingHighlight: "Elevate",
    ctaHeading2: "Your Business?",
    ctaDesc: "Whether you need a custom web app, AI automation, or stunning content — rasel.cloud is your digital partner.",
    ctaCta1: "Get a Free Consultation",
    ctaCta2: "See Our Work",

    contactTag: "Get in Touch",
    contactSubheading: "Tell us about your project — we'll respond within 24 hours.",
    contactHeading: "Let's Build",
    contactHeadingHighlight: "Together",
    contactName: "Name",
    contactNamePlaceholder: "Your name",
    contactEmail: "Email",
    contactEmailPlaceholder: "you@email.com",
    contactDetails: "Tell Us About Your Project",
    contactDetailsPlaceholder: "Describe your project, goals, timeline & budget...",
    contactSend: "Send Inquiry",
    contactSuccess: "Inquiry sent! We'll reply within 24 hours.",
    contactError: "Failed to send. Please try again.",

    footerText: "Your Digital Partner for Growth.",

    // Pricing
    pricingTag: "Choose Your Plan",
    pricingHeading: "Transparent",
    pricingHeadingHighlight: "Pricing",
    pricingBasic: "Basic",
    pricingStandard: "Standard",
    pricingPremium: "Premium",
    pricingPopular: "Most Popular",
    pricingBasicPrice: "$299",
    pricingStandardPrice: "$699",
    pricingPremiumPrice: "$1,499",
    pricingBasicDesc: "Perfect for startups and small businesses",
    pricingStandardDesc: "Best for growing businesses",
    pricingPremiumDesc: "Enterprise-grade solutions",
    pricingCta: "Get Started",
    pricingBasicFeatures: ["Landing Page", "Mobile Responsive", "Basic SEO", "Contact Form", "3 Revisions"],
    pricingStandardFeatures: ["Multi-Page Website", "Admin Dashboard", "Advanced SEO", "AI Chatbot", "CMS Integration", "10 Revisions"],
    pricingPremiumFeatures: ["Custom Web App", "Full Admin Panel", "AI Automation Suite", "Priority Support", "Video Content", "Unlimited Revisions"],

    // Team
    teamTag: "Meet the Team",
    teamHeading: "Our",
    teamHeadingHighlight: "Experts",

    // Why Partner
    whyTag: "Why Choose Us",
    whyHeading: "Why Partner",
    whyHeadingHighlight: "With Us",
    why1Title: "24/7 Support",
    why1Desc: "Round-the-clock availability for all your digital needs.",
    why2Title: "Premium Quality",
    why2Desc: "Every pixel, every line of code meets the highest standards.",
    why3Title: "Fast Delivery",
    why3Desc: "We respect deadlines without compromising on quality.",
    why4Title: "Scalable Solutions",
    why4Desc: "Built to grow with your business from day one.",
    why5Title: "Transparent Pricing",
    why5Desc: "No hidden fees. Clear milestones and deliverables.",
    why6Title: "Proven Results",
    why6Desc: "Track record of 50+ successful projects across industries.",

    // Cart
    cartTitle: "Your Cart",
    cartEmpty: "Your cart is empty",
    cartTotal: "Total",
    cartCheckout: "Proceed to Checkout",
    cartRemove: "Remove",
    cartAdded: "Added to cart!",

    // Checkout
    checkoutTitle: "Checkout",
    checkoutName: "Full Name",
    checkoutEmail: "Email Address",
    checkoutPhone: "Phone Number",
    checkoutMessage: "Additional Notes",
    checkoutSubmit: "Place Order",
    checkoutSuccess: "Order Placed Successfully!",
    checkoutSuccessDesc: "We'll contact you within 24 hours to discuss your project.",
    checkoutBack: "Back to Home",

    // About page
    aboutTag: "About Us",
    aboutHeading: "The Team Behind",
    aboutHeadingHighlight: "rasel.cloud",
    aboutSubheading: "We are a full-service digital agency headquartered in Bangladesh, helping businesses across the globe build powerful web products, automate workflows with AI, and grow their digital presence.",
    aboutStoryTitle: "Our Story",
    aboutStory1: "rasel.cloud was founded in 2020 by a group of passionate developers and designers who believed that every business — regardless of size — deserves enterprise-grade digital solutions at accessible prices.",
    aboutStory2: "Starting with web development, we quickly expanded into AI automation, SEO, video production, and brand design as our clients' needs grew. Today, rasel.cloud is a trusted partner for startups, SMEs, and enterprise clients worldwide.",
    aboutStory3: "We operate with a remote-first culture, drawing talent from across Bangladesh and collaborating with specialists globally. Our flat structure means every client gets direct access to the people actually building their product.",
    aboutDiffTitle: "Why We're Different",
    aboutVal1Title: "Mission-Driven",    aboutVal1Desc: "Every project is a step toward transforming a business. We treat your goals as our own.",
    aboutVal2Title: "Speed & Quality",   aboutVal2Desc: "Fast delivery without compromising on pixel-perfect quality and production-ready code.",
    aboutVal3Title: "Client-Centric",   aboutVal3Desc: "24/7 support, transparent communication, and unlimited post-delivery assistance.",
    aboutVal4Title: "Global Reach",     aboutVal4Desc: "Serving clients from Bangladesh to Europe, America, and beyond since 2020.",
    aboutVal5Title: "Proven Results",   aboutVal5Desc: "200+ projects completed, 98% client satisfaction, and growing every month.",
    aboutVal6Title: "Expert Team",      aboutVal6Desc: "A hand-picked team of designers, developers, AI engineers, and SEO specialists.",

    // Contact section extras
    contactSendTitle: "Send a Message",
    contactDirectTitle: "Contact Directly",
    contactSkipDesc: "Skip the form — reach us on your favourite platform.",
    contactOfficeHours: "Office Hours",
    contactFormSending: "Sending...",
    contactServiceLabel: "Service interested in",
    contactPhoneLabel: "Phone (optional)",
    contactSelectService: "— Select a service —",
  },
  bn: {
    navHome: "হোম",
    navServices: "সেবা",
    navPricing: "মূল্যতালিকা",
    navPortfolio: "আমাদের ডেমো",
    navTeam: "আমাদের টিম",
    navWhyUs: "কেন আমরা",
    navContact: "যোগাযোগ",
    navAbout: "আমাদের সম্পর্কে",
    navFaq: "সাধারণ প্রশ্ন",
    navPrivacy: "গোপনীয়তা নীতি",
    navTerms: "শর্তাবলী",
    navCta: "শুরু করুন",
    navMore: "আরও",
    navSectionMain: "মেনু",
    navSectionInfo: "তথ্য",
    navSectionAccount: "অ্যাকাউন্ট",
    navProfile: "প্রোফাইল",
    navAdminPanel: "অ্যাডমিন প্যানেল",
    navSignOut: "সাইন আউট",
    navSignIn: "সাইন ইন",
    navCreateAccount: "অ্যাকাউন্ট তৈরি করুন",
    cart: "কার্ট",

    heroBadge: "রাসেল ক্লাউড টিম — ফুল-সার্ভিস ডিজিটাল এজেন্সি",
    heroHeading1: "আপনার ডিজিটাল উপস্থিতি",
    heroHeading2: "তৈরি, বৃদ্ধি ও রূপান্তর",
    heroHeading3: "করি।",
    heroSub1: "স্বাগতম",
    heroName: "rasel.cloud",
    heroSub2: "-এ — কাস্টম ওয়েব, AI অটোমেশন, SEO এবং ক্রিয়েটিভ মিডিয়া প্রদানকারী ডিজিটাল এজেন্সি।",
    heroCtaPrimary: "যোগাযোগ করুন",
    heroCtaSecondary: "আমাদের ডেমো",
    heroProjects: "প্রজেক্ট",
    heroClients: "ক্লায়েন্ট",
    heroYears: "বছর",
    typewriterWords: ["ওয়েব ডেভেলপমেন্ট", "AI অটোমেশন", "SEO ও গ্রোথ", "ভিডিও এডিটিং", "ব্র্যান্ড ডিজাইন", "অ্যাডমিন প্যানেল"],

    statsProjects: "প্রজেক্ট সম্পন্ন",
    statsClients: "সন্তুষ্ট ক্লায়েন্ট",
    statsSatisfaction: "ক্লায়েন্ট সন্তুষ্টি",
    statsSupport: "সাপোর্ট উপলব্ধ",

    servicesTag: "আমরা যা অফার করি",
    servicesHeading: "আমাদের মূল",
    servicesHeadingHighlight: "সেবাসমূহ",
    svcWebTitle: "কাস্টম ওয়েব ও অ্যাডমিন প্যানেল",
    svcWebDesc: "এন্টারপ্রাইজ-গ্রেড ওয়েবসাইট, অ্যাডমিন ড্যাশবোর্ড, ই-কমার্স এবং ম্যানেজমেন্ট সিস্টেম।",
    svcAiTitle: "AI এজেন্ট অটোমেশন",
    svcAiDesc: "সোশ্যাল মিডিয়া, চ্যাটবট এবং বিজনেস ওয়ার্কফ্লোতে AI এজেন্ট ডিপ্লয় করুন।",
    svcSeoTitle: "SEO ও ডিজিটাল গ্রোথ",
    svcSeoDesc: "টেকনিক্যাল SEO, কন্টেন্ট স্ট্র্যাটেজি এবং পারফরম্যান্স অপটিমাইজেশন।",
    svcCreativeTitle: "ক্রিয়েটিভ মিডিয়া ও ডিজাইন",
    svcCreativeDesc: "ভিডিও এডিটিং, মোশন গ্রাফিক্স, বায়োগ্রাফি ডিজাইন এবং ব্র্যান্ড আইডেন্টিটি।",
    svcLearnMore: "বিস্তারিত দেখুন",
    svcAddToCart: "কার্টে যোগ করুন",
    svcBuyNow: "এখনই কিনুন",

    processTag: "আমরা কিভাবে কাজ করি",
    processHeading: "আমাদের",
    processHeadingHighlight: "পদ্ধতি",
    proc1Title: "আবিষ্কার ও কৌশল",
    proc1Desc: "আপনার ব্যবসা বিশ্লেষণ করে কাস্টম কৌশল তৈরি করি।",
    proc2Title: "ডিজাইন ও প্রোটোটাইপ",
    proc2Desc: "পিক্সেল-পারফেক্ট ডিজাইন এবং ইন্টারেক্টিভ প্রোটোটাইপ।",
    proc3Title: "ডেভেলপমেন্ট ও ইন্টিগ্রেশন",
    proc3Desc: "অত্যাধুনিক প্রযুক্তি ও AI ইন্টিগ্রেশন।",
    proc4Title: "লঞ্চ ও স্কেল",
    proc4Desc: "টেস্টিং, ডিপ্লয়মেন্ট ও গ্রোথ স্ট্র্যাটেজি।",

    portfolioTag: "লাইভ ডেমো",
    portfolioHeading: "আমাদের",
    portfolioHeadingHighlight: "ডেমোসমূহ",
    port1Title: "BD Order Solution",
    port1Cat: "ই-কমার্স প্ল্যাটফর্ম",
    port1Desc: "বিকাশ/নগদ পেমেন্ট ইন্টিগ্রেশন সহ WooCommerce চেকআউট ম্যানেজার।",
    port1Metric: "বিক্রয় ৪০% বৃদ্ধি",
    port2Title: "কারিয়ানা কুরআন ওয়েব অ্যাপ",
    port2Cat: "ফুল-স্ট্যাক ওয়েব অ্যাপ",
    port2Desc: "কুরআন পড়া ও নামাজের সময় সহ ইসলামিক টুলস স্যুট।",
    port2Metric: "১০ হাজার+ সক্রিয় ব্যবহারকারী",
    port3Title: "হার্বো কিউর ম্যানেজমেন্ট",
    port3Cat: "এন্টারপ্রাইজ ড্যাশবোর্ড",
    port3Desc: "রোগী ব্যবস্থাপনা ও অ্যানালিটিক্স ড্যাশবোর্ড।",
    port3Metric: "দক্ষতা ৬০% বৃদ্ধি",
    port4Title: "AI এজেন্ট ও DevOps",
    port4Cat: "AI অটোমেশন",
    port4Desc: "সোশ্যাল মিডিয়া ও কন্টেন্ট জেনারেশনের জন্য AI এজেন্ট।",
    port4Metric: "৫x দ্রুত অপারেশন",

    testTag: "ক্লায়েন্ট মতামত",
    testHeading: "ক্লায়েন্টরা যা",
    testHeadingHighlight: "বলে",

    techTag: "আমাদের টেক অস্ত্রাগার",
    techHeading: "টেক",
    techHeadingHighlight: "স্ট্যাক",

    roiTag: "প্রভাব দেখুন",
    roiHeading: "AI ROI",
    roiHeadingHighlight: "ক্যালকুলেটর",
    roiHoursLabel: "ম্যানুয়াল কাজে সাপ্তাহিক ঘণ্টা",
    roiRateLabel: "আপনার ঘণ্টার রেট ($)",
    roiResult: "আমাদের AI অটোমেশনে আপনি সাশ্রয় করতে পারেন",
    roiHours: "ঘণ্টা/সপ্তাহ",
    roiMoney: "/বছর",
    roiCta: "আপনার ব্যবসা অটোমেট করুন",

    faqTag: "সাধারণ প্রশ্ন",
    faqHeading: "সচরাচর",
    faqHeadingHighlight: "জিজ্ঞাসা",
    faq1Q: "rasel.cloud কি কি সেবা দেয়?",
    faq1A: "কাস্টম ওয়েব, অ্যাডমিন প্যানেল, AI অটোমেশন, SEO, ভিডিও এডিটিং ও ব্র্যান্ড আইডেন্টিটি।",
    faq2Q: "একটি প্রজেক্টে কত সময় লাগে?",
    faq2A: "ল্যান্ডিং পেজ: ১-২ সপ্তাহ, অ্যাডমিন প্যানেল: ৩-৬ সপ্তাহ, AI: ৪-৮ সপ্তাহ।",
    faq3Q: "আপনারা কি বড় কোম্পানির সাথে কাজ করেন?",
    faq3A: "অবশ্যই। এন্টারপ্রাইজ-গ্রেড সমাধানে বিশেষজ্ঞ।",
    faq4Q: "প্রাইসিং মডেল কী?",
    faq4A: "ফিক্সড-প্রাইস, মাইলস্টোন-ভিত্তিক এবং রিটেইনার মডেল।",
    faq5Q: "SEO ও মার্কেটিং হ্যান্ডেল করেন?",
    faq5A: "হ্যাঁ! ওয়েবসাইট তৈরি থেকে গুগলে র‍্যাংক করা পর্যন্ত সবকিছু।",

    ctaHeading1: "আপনার ব্যবসা",
    ctaHeadingHighlight: "উন্নীত",
    ctaHeading2: "করতে প্রস্তুত?",
    ctaDesc: "কাস্টম ওয়েব অ্যাপ, AI অটোমেশন, বা ক্রিয়েটিভ কন্টেন্ট — rasel.cloud আপনার ডিজিটাল পার্টনার।",
    ctaCta1: "ফ্রি পরামর্শ নিন",
    ctaCta2: "আমাদের কাজ দেখুন",

    contactTag: "যোগাযোগ করুন",
    contactSubheading: "আপনার প্রজেক্ট সম্পর্কে জানান — আমরা ২৪ ঘণ্টার মধ্যে সাড়া দেবো।",
    contactHeading: "একসাথে",
    contactHeadingHighlight: "তৈরি করি",
    contactName: "নাম",
    contactNamePlaceholder: "আপনার নাম",
    contactEmail: "ইমেইল",
    contactEmailPlaceholder: "you@email.com",
    contactDetails: "আপনার প্রজেক্ট সম্পর্কে বলুন",
    contactDetailsPlaceholder: "আপনার প্রজেক্ট, লক্ষ্য, সময়সীমা ও বাজেট বর্ণনা করুন...",
    contactSend: "অনুসন্ধান পাঠান",
    contactSuccess: "সফলভাবে পাঠানো হয়েছে! ২৪ ঘণ্টার মধ্যে উত্তর দেব।",
    contactError: "পাঠাতে ব্যর্থ। আবার চেষ্টা করুন।",

    footerText: "আপনার গ্রোথ পার্টনার।",

    pricingTag: "আপনার প্ল্যান বেছে নিন",
    pricingHeading: "স্বচ্ছ",
    pricingHeadingHighlight: "মূল্য",
    pricingBasic: "বেসিক",
    pricingStandard: "স্ট্যান্ডার্ড",
    pricingPremium: "প্রিমিয়াম",
    pricingPopular: "সবচেয়ে জনপ্রিয়",
    pricingBasicPrice: "$২৯৯",
    pricingStandardPrice: "$৬৯৯",
    pricingPremiumPrice: "$১,৪৯৯",
    pricingBasicDesc: "স্টার্টআপ ও ছোট ব্যবসার জন্য",
    pricingStandardDesc: "বর্ধনশীল ব্যবসার জন্য সেরা",
    pricingPremiumDesc: "এন্টারপ্রাইজ-গ্রেড সমাধান",
    pricingCta: "শুরু করুন",
    pricingBasicFeatures: ["ল্যান্ডিং পেজ", "মোবাইল রেসপন্সিভ", "বেসিক SEO", "কন্টাক্ট ফর্ম", "৩টি রিভিশন"],
    pricingStandardFeatures: ["মাল্টি-পেজ ওয়েবসাইট", "অ্যাডমিন ড্যাশবোর্ড", "অ্যাডভান্সড SEO", "AI চ্যাটবট", "CMS ইন্টিগ্রেশন", "১০টি রিভিশন"],
    pricingPremiumFeatures: ["কাস্টম ওয়েব অ্যাপ", "ফুল অ্যাডমিন প্যানেল", "AI অটোমেশন স্যুট", "প্রায়রিটি সাপোর্ট", "ভিডিও কন্টেন্ট", "আনলিমিটেড রিভিশন"],

    teamTag: "টিমের সাথে পরিচিত হন",
    teamHeading: "আমাদের",
    teamHeadingHighlight: "বিশেষজ্ঞরা",

    whyTag: "কেন আমাদের বেছে নেবেন",
    whyHeading: "কেন পার্টনার",
    whyHeadingHighlight: "আমাদের সাথে",
    why1Title: "২৪/৭ সাপোর্ট",
    why1Desc: "আপনার সকল ডিজিটাল প্রয়োজনে সার্বক্ষণিক উপলব্ধ।",
    why2Title: "প্রিমিয়াম কোয়ালিটি",
    why2Desc: "প্রতিটি পিক্সেল, প্রতিটি লাইন কোড সর্বোচ্চ মানসম্পন্ন।",
    why3Title: "দ্রুত ডেলিভারি",
    why3Desc: "কোয়ালিটি বজায় রেখে সময়মত ডেলিভারি।",
    why4Title: "স্কেলেবল সমাধান",
    why4Desc: "প্রথম দিন থেকেই আপনার ব্যবসার সাথে বৃদ্ধির জন্য তৈরি।",
    why5Title: "স্বচ্ছ মূল্য",
    why5Desc: "কোনো গোপন ফি নেই। স্পষ্ট মাইলস্টোন ও ডেলিভারেবল।",
    why6Title: "প্রমাণিত ফলাফল",
    why6Desc: "বিভিন্ন ইন্ডাস্ট্রিতে ৫০+ সফল প্রজেক্টের ট্র্যাক রেকর্ড।",

    cartTitle: "আপনার কার্ট",
    cartEmpty: "আপনার কার্ট খালি",
    cartTotal: "মোট",
    cartCheckout: "চেকআউটে যান",
    cartRemove: "সরান",
    cartAdded: "কার্টে যোগ হয়েছে!",

    checkoutTitle: "চেকআউট",
    checkoutName: "পুরো নাম",
    checkoutEmail: "ইমেইল ঠিকানা",
    checkoutPhone: "ফোন নম্বর",
    checkoutMessage: "অতিরিক্ত নোট",
    checkoutSubmit: "অর্ডার দিন",
    checkoutSuccess: "অর্ডার সফলভাবে দেওয়া হয়েছে!",
    checkoutSuccessDesc: "আপনার প্রজেক্ট নিয়ে ২৪ ঘণ্টার মধ্যে যোগাযোগ করব।",
    checkoutBack: "হোমে ফিরে যান",

    // About page
    aboutTag: "আমাদের সম্পর্কে",
    aboutHeading: "যারা পরিচালনা করে",
    aboutHeadingHighlight: "rasel.cloud",
    aboutSubheading: "আমরা বাংলাদেশ ভিত্তিক একটি ফুল-সার্ভিস ডিজিটাল এজেন্সি, যা বিশ্বব্যাপী ব্যবসায়িক প্রতিষ্ঠানের জন্য ওয়েব পণ্য তৈরি, AI অটোমেশন এবং ডিজিটাল গ্রোথ নিশ্চিত করে।",
    aboutStoryTitle: "আমাদের গল্প",
    aboutStory1: "rasel.cloud ২০২০ সালে উৎসাহী ডেভেলপার ও ডিজাইনারদের একটি দল দ্বারা প্রতিষ্ঠিত হয়, যারা বিশ্বাস করতেন যে প্রতিটি ব্যবসা — আকার নির্বিশেষে — সাশ্রয়ী মূল্যে এন্টারপ্রাইজ-গ্রেড সমাধান পাওয়ার যোগ্য।",
    aboutStory2: "ওয়েব ডেভেলপমেন্ট দিয়ে শুরু করে আমরা দ্রুত AI অটোমেশন, SEO, ভিডিও প্রোডাকশন এবং ব্র্যান্ড ডিজাইনে প্রসারিত হয়েছি। আজ rasel.cloud স্টার্টআপ, SME এবং বৈশ্বিক এন্টারপ্রাইজ ক্লায়েন্টদের বিশ্বস্ত অংশীদার।",
    aboutStory3: "আমরা রিমোট-ফার্স্ট সংস্কৃতিতে পরিচালিত হই, বাংলাদেশ জুড়ে প্রতিভাবান মানুষদের সংযুক্ত করে বিশ্বের বিশেষজ্ঞদের সাথে সহযোগিতা করি।",
    aboutDiffTitle: "কেন আমরা আলাদা",
    aboutVal1Title: "লক্ষ্যভিত্তিক",        aboutVal1Desc: "প্রতিটি প্রজেক্ট একটি ব্যবসার রূপান্তরের পদক্ষেপ। আপনার লক্ষ্যকে আমরা নিজেদের লক্ষ্য মনে করি।",
    aboutVal2Title: "গতি ও মান",           aboutVal2Desc: "পিক্সেল-পারফেক্ট মান বজায় রেখে দ্রুত ডেলিভারি।",
    aboutVal3Title: "ক্লায়েন্ট-কেন্দ্রিক", aboutVal3Desc: "২৪/৭ সাপোর্ট, স্বচ্ছ যোগাযোগ এবং ডেলিভারির পরেও সহায়তা।",
    aboutVal4Title: "বৈশ্বিক উপস্থিতি",    aboutVal4Desc: "২০২০ সাল থেকে বাংলাদেশ থেকে ইউরোপ, আমেরিকা পর্যন্ত সেবা প্রদান।",
    aboutVal5Title: "প্রমাণিত ফলাফল",       aboutVal5Desc: "২০০+ প্রজেক্ট সম্পন্ন, ৯৮% ক্লায়েন্ট সন্তুষ্টি।",
    aboutVal6Title: "বিশেষজ্ঞ টিম",        aboutVal6Desc: "ডিজাইনার, ডেভেলপার, AI ইঞ্জিনিয়ার এবং SEO বিশেষজ্ঞদের বাছাই করা দল।",

    // Contact section extras
    contactSendTitle: "বার্তা পাঠান",
    contactDirectTitle: "সরাসরি যোগাযোগ",
    contactSkipDesc: "ফর্ম বাদ দিয়ে স্বাচ্ছন্দ প্ল্যাটফর্মে যোগাযোগ করুন।",
    contactOfficeHours: "অফিস সময়",
    contactFormSending: "পাঠানো হচ্ছে...",
    contactServiceLabel: "আগ্রহী সেবা",
    contactPhoneLabel: "ফোন (স্বেচ্ছায়)",
    contactSelectService: "— একটি সেবা বেছুন —",
  },
  hi: {
    navHome: "होम",
    navServices: "सेवाएं",
    navPricing: "मूल्य",
    navPortfolio: "पोर्टफोलियो",
    navTeam: "टीम",
    navWhyUs: "क्यों हम",
    navContact: "संपर्क",
    navAbout: "हमारे बारे में",
    navFaq: "सामान्य प्रश्न",
    navPrivacy: "गोपनीयता नीति",
    navTerms: "नियम एवं शर्तें",
    navCta: "शुरू करें",
    navMore: "अधिक",
    navSectionMain: "मेनू",
    navSectionInfo: "जानकारी",
    navSectionAccount: "खाता",
    navProfile: "प्रोफाइल",
    navAdminPanel: "एडमिन पैनल",
    navSignOut: "साइन आउट",
    navSignIn: "साइन इन",
    navCreateAccount: "खाता बनाएं",
    cart: "कार्ट",

    heroBadge: "रसेल क्लाउड टीम — फुल-सर्विस डिजिटल एजेंसी",
    heroHeading1: "हम बनाते, बढ़ाते और",
    heroHeading2: "रूपांतरित",
    heroHeading3: "करते हैं आपकी डिजिटल उपस्थिति।",
    heroSub1: "स्वागत है",
    heroName: "rasel.cloud",
    heroSub2: " में — कस्टम वेब, AI ऑटोमेशन, SEO और क्रिएटिव मीडिया प्रदान करने वाली डिजिटल एजेंसी।",
    heroCtaPrimary: "मुफ्त परामर्श लें",
    heroCtaSecondary: "सेवाएं देखें",
    heroProjects: "प्रोजेक्ट",
    heroClients: "क्लाइंट",
    heroYears: "साल",
    typewriterWords: ["वेब डेवलपमेंट", "AI ऑटोमेशन", "SEO और ग्रोथ", "वीडियो एडिटिंग", "ब्रांड डिज़ाइन", "एडमिन पैनल"],

    statsProjects: "प्रोजेक्ट पूरे",
    statsClients: "खुश क्लाइंट",
    statsSatisfaction: "क्लाइंट संतुष्टि",
    statsSupport: "सपोर्ट उपलब्ध",

    servicesTag: "हम क्या प्रदान करते हैं",
    servicesHeading: "हमारी मुख्य",
    servicesHeadingHighlight: "सेवाएं",
    svcWebTitle: "कस्टम वेब और एडमिन पैनल",
    svcWebDesc: "एंटरप्राइज-ग्रेड वेबसाइट, एडमिन डैशबोर्ड, ई-कॉमर्स और मैनेजमेंट सिस्टम।",
    svcAiTitle: "AI एजेंट ऑटोमेशन",
    svcAiDesc: "सोशल मीडिया, चैटबॉट और बिजनेस वर्कफ्लो में AI एजेंट डिप्लॉय करें।",
    svcSeoTitle: "SEO और डिजिटल ग्रोथ",
    svcSeoDesc: "टेक्निकल SEO, कंटेंट स्ट्रैटेजी और परफॉर्मेंस ऑप्टिमाइज़ेशन।",
    svcCreativeTitle: "क्रिएटिव मीडिया और डिज़ाइन",
    svcCreativeDesc: "वीडियो एडिटिंग, मोशन ग्राफिक्स, बायोग्राफी डिज़ाइन और ब्रांड आइडेंटिटी।",
    svcLearnMore: "और जानें",
    svcAddToCart: "कार्ट में जोड़ें",
    svcBuyNow: "अभी खरीदें",

    processTag: "हम कैसे काम करते हैं",
    processHeading: "हमारी",
    processHeadingHighlight: "प्रक्रिया",
    proc1Title: "खोज और रणनीति",
    proc1Desc: "आपके बिजनेस का विश्लेषण करके कस्टम रणनीति बनाते हैं।",
    proc2Title: "डिज़ाइन और प्रोटोटाइप",
    proc2Desc: "पिक्सेल-परफेक्ट डिज़ाइन और इंटरैक्टिव प्रोटोटाइप।",
    proc3Title: "डेवलपमेंट और इंटीग्रेशन",
    proc3Desc: "AI इंटीग्रेशन और SEO ऑप्टिमाइज़ेशन सहित।",
    proc4Title: "लॉन्च और स्केल",
    proc4Desc: "टेस्टिंग, डिप्लॉयमेंट और ग्रोथ स्ट्रैटेजी।",

    portfolioTag: "चुनिंदा कार्य",
    portfolioHeading: "पोर्टफोलियो",
    portfolioHeadingHighlight: "शोकेस",
    port1Title: "BD Order Solution",
    port1Cat: "ई-कॉमर्स प्लेटफॉर्म",
    port1Desc: "bKash/Nagad पेमेंट इंटीग्रेशन सहित WooCommerce चेकआउट मैनेजर।",
    port1Metric: "बिक्री 40% बढ़ी",
    port2Title: "करियाना कुरान वेब ऐप",
    port2Cat: "फुल-स्टैक वेब ऐप",
    port2Desc: "कुरान पढ़ने और नमाज़ के समय सहित इस्लामिक टूल्स सूट।",
    port2Metric: "10K+ सक्रिय उपयोगकर्ता",
    port3Title: "हर्बो क्योर मैनेजमेंट",
    port3Cat: "एंटरप्राइज डैशबोर्ड",
    port3Desc: "रोगी प्रबंधन और एनालिटिक्स डैशबोर्ड।",
    port3Metric: "दक्षता 60% बढ़ी",
    port4Title: "AI एजेंट और DevOps",
    port4Cat: "AI ऑटोमेशन",
    port4Desc: "सोशल मीडिया और कंटेंट जनरेशन के लिए AI एजेंट।",
    port4Metric: "5x तेज़ ऑपरेशन",

    testTag: "क्लाइंट कहानियां",
    testHeading: "क्लाइंट क्या",
    testHeadingHighlight: "कहते हैं",

    techTag: "हमारा टेक शस्त्रागार",
    techHeading: "टेक",
    techHeadingHighlight: "स्टैक",

    roiTag: "प्रभाव देखें",
    roiHeading: "AI ROI",
    roiHeadingHighlight: "कैलकुलेटर",
    roiHoursLabel: "मैनुअल कार्यों में साप्ताहिक घंटे",
    roiRateLabel: "आपकी घंटे की दर ($)",
    roiResult: "हमारे AI ऑटोमेशन से आप बचा सकते हैं",
    roiHours: "घंटे/सप्ताह",
    roiMoney: "/वर्ष",
    roiCta: "अपना बिजनेस ऑटोमेट करें",

    faqTag: "सामान्य प्रश्न",
    faqHeading: "अक्सर",
    faqHeadingHighlight: "पूछे जाने वाले",
    faq1Q: "rasel.cloud क्या सेवाएं देता है?",
    faq1A: "कस्टम वेब, एडमिन पैनल, AI ऑटोमेशन, SEO, वीडियो एडिटिंग और ब्रांड आइडेंटिटी।",
    faq2Q: "एक प्रोजेक्ट में कितना समय लगता है?",
    faq2A: "लैंडिंग पेज: 1-2 सप्ताह, एडमिन पैनल: 3-6 सप्ताह, AI: 4-8 सप्ताह।",
    faq3Q: "क्या आप बड़ी कंपनियों के साथ काम करते हैं?",
    faq3A: "बिल्कुल। हम एंटरप्राइज-ग्रेड समाधानों में विशेषज्ञ हैं।",
    faq4Q: "प्राइसिंग मॉडल क्या है?",
    faq4A: "फिक्स्ड-प्राइस, माइलस्टोन-बेस्ड और रिटेनर मॉडल।",
    faq5Q: "क्या SEO भी हैंडल करते हैं?",
    faq5A: "हां! वेबसाइट बनाने से लेकर Google पर रैंक करने तक सब कुछ।",

    ctaHeading1: "अपने बिजनेस को",
    ctaHeadingHighlight: "ऊपर",
    ctaHeading2: "ले जाने के लिए तैयार?",
    ctaDesc: "कस्टम वेब ऐप, AI ऑटोमेशन, या शानदार कंटेंट — rasel.cloud आपका डिजिटल पार्टनर।",
    ctaCta1: "मुफ्त परामर्श लें",
    ctaCta2: "हमारा काम देखें",

    contactTag: "संपर्क करें",
    contactHeading: "साथ मिलकर",
    contactHeadingHighlight: "बनाएं",
    contactName: "नाम",
    contactNamePlaceholder: "आपका नाम",
    contactEmail: "ईमेल",
    contactEmailPlaceholder: "you@email.com",
    contactDetails: "अपने प्रोजेक्ट के बारे में बताएं",
    contactDetailsPlaceholder: "किस सेवा में रुचि है?",
    contactSend: "पूछताछ भेजें",
    contactSuccess: "सफलतापूर्वक भेजा गया! 24 घंटे में जवाब देंगे।",
    contactError: "भेजने में विफल। कृपया पुनः प्रयास करें।",

    footerText: "आपका ग्रोथ पार्टनर।",

    pricingTag: "अपना प्लान चुनें",
    pricingHeading: "पारदर्शी",
    pricingHeadingHighlight: "मूल्य",
    pricingBasic: "बेसिक",
    pricingStandard: "स्टैंडर्ड",
    pricingPremium: "प्रीमियम",
    pricingPopular: "सबसे लोकप्रिय",
    pricingBasicPrice: "$299",
    pricingStandardPrice: "$699",
    pricingPremiumPrice: "$1,499",
    pricingBasicDesc: "स्टार्टअप और छोटे बिजनेस के लिए",
    pricingStandardDesc: "बढ़ते बिजनेस के लिए सर्वश्रेष्ठ",
    pricingPremiumDesc: "एंटरप्राइज-ग्रेड समाधान",
    pricingCta: "शुरू करें",
    pricingBasicFeatures: ["लैंडिंग पेज", "मोबाइल रिस्पॉन्सिव", "बेसिक SEO", "कॉन्टैक्ट फॉर्म", "3 रिवीज़न"],
    pricingStandardFeatures: ["मल्टी-पेज वेबसाइट", "एडमिन डैशबोर्ड", "एडवांस्ड SEO", "AI चैटबॉट", "CMS इंटीग्रेशन", "10 रिवीज़न"],
    pricingPremiumFeatures: ["कस्टम वेब ऐप", "फुल एडमिन पैनल", "AI ऑटोमेशन सूट", "प्रायोरिटी सपोर्ट", "वीडियो कंटेंट", "अनलिमिटेड रिवीज़न"],

    teamTag: "टीम से मिलें",
    teamHeading: "हमारे",
    teamHeadingHighlight: "विशेषज्ञ",

    whyTag: "हमें क्यों चुनें",
    whyHeading: "पार्टनर क्यों",
    whyHeadingHighlight: "हमारे साथ",
    why1Title: "24/7 सपोर्ट",
    why1Desc: "आपकी सभी डिजिटल ज़रूरतों के लिए हर समय उपलब्ध।",
    why2Title: "प्रीमियम क्वालिटी",
    why2Desc: "हर पिक्सेल, कोड की हर लाइन सर्वोच्च मानकों को पूरा करती है।",
    why3Title: "तेज़ डिलीवरी",
    why3Desc: "क्वालिटी से समझौता किए बिना समय पर डिलीवरी।",
    why4Title: "स्केलेबल समाधान",
    why4Desc: "पहले दिन से आपके बिजनेस के साथ बढ़ने के लिए बना।",
    why5Title: "पारदर्शी मूल्य",
    why5Desc: "कोई छिपी फीस नहीं। स्पष्ट माइलस्टोन।",
    why6Title: "प्रमाणित परिणाम",
    why6Desc: "विभिन्न उद्योगों में 50+ सफल प्रोजेक्ट।",

    cartTitle: "आपका कार्ट",
    cartEmpty: "आपका कार्ट खाली है",
    cartTotal: "कुल",
    cartCheckout: "चेकआउट करें",
    cartRemove: "हटाएं",
    cartAdded: "कार्ट में जोड़ा गया!",

    checkoutTitle: "चेकआउट",
    checkoutName: "पूरा नाम",
    checkoutEmail: "ईमेल पता",
    checkoutPhone: "फ़ोन नंबर",
    checkoutMessage: "अतिरिक्त नोट",
    checkoutSubmit: "ऑर्डर दें",
    checkoutSuccess: "ऑर्डर सफलतापूर्वक दिया गया!",
    checkoutSuccessDesc: "हम 24 घंटे में आपसे संपर्क करेंगे।",
    checkoutBack: "होम पर वापस जाएं",
  },
};

type Translations = typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // Always start with "en" so server HTML matches the first client render.
  // We track `hydrated` separately to ensure we NEVER change the language
  // while React is still reconciling Suspense boundaries.
  const [lang, setLangState] = useState<Lang>("en");
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    // Mark hydration complete on the next tick (after React has committed
    // and all Suspense boundaries have resolved their client HTML).
    const timer = setTimeout(() => {
      setHydrated(true);

      // Step 1: restore stored preference
      const stored = localStorage.getItem("lang");
      if (stored === "bn" || stored === "en") {
        setLangState(stored as Lang);
        return;
      }
      // Step 2: country-code shortcut — default to 'bn' for Bangladesh
      const country = localStorage.getItem("rc_country");
      // No stored preference → default to Bengali (BD-first platform)
      if (country === "BD" || country === null) { setLangState("bn"); localStorage.setItem("lang", "bn"); return; }
      if (country !== null) return; // other country → keep "en"
      // Step 3: geo-detect (first visit, no stored data)
      import("@/lib/geoLocale").then(({ detectGeoLocale }) =>
        detectGeoLocale().then(({ lang: detected }) => {
          setLangState(detected as Lang);
          localStorage.setItem("lang", detected);
        })
      );
    }, 0);

    return () => clearTimeout(timer);
  }, []);

  const handleSetLang = (newLang: Lang) => {
    setLangState(newLang);
    localStorage.setItem("lang", newLang);
  };

  // During hydration, always expose "en" regardless of detected lang.
  // After hydration is confirmed complete, expose the real lang.
  const effectiveLang: Lang = hydrated ? lang : "en";

  return (
    <LanguageContext.Provider value={{ lang: effectiveLang, setLang: handleSetLang, t: translations[effectiveLang] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

